[package]
name = "rde-repl"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
rde-core = { workspace = true }
rde-win32 = { workspace = true }
rde-symbols = { workspace = true }
rde-breakpoint = { workspace = true }
rde-pretty-print = { workspace = true }
rde-tokio = { workspace = true }
rde-orchestrator = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
mockall = { workspace = true }
insta = { workspace = true }
