[package]
name = "rde-symbols"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
rde-core = { workspace = true }
libloading = { workspace = true }
rustc-demangle = { workspace = true }
capstone = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
windows = { workspace = true }

[dev-dependencies]
mockall = { workspace = true }
