[package]
name = "rde-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
tokio = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
uuid = { version = "1.8", features = ["v4"] }
capstone = "0.12"


[dev-dependencies]
mockall = { workspace = true }
